numero = str(input('Digite um número: ')).strip(numero[1])
print('unidade: {}'.format(numero[len(numero)-1]))
print('Dezena: {}'.format(numero[len(numero)-2]))
print('Centena: {}'.format(numero[len(numero)-3]))
print('Milhar: {}'.format(numero[len(numero)-4]))
